### ISSUE TITLE
Let the user override scrollTo

### ISSUE THREAD

**Issue by MartinSStewart** [WhileTruu/elm-smooth-scroll#4]
For the user it's frustrating if they try to scroll while `scrollTo` is moving their viewport. It would be nice if there was a `scrollToUserOverridable` (maybe with a better name) that would stop scrolling if it detected that the user was scrolling.

I think this could be achieved by having `step` check if the current viewport position is where it's expected to be if the user hasn't scrolled. If this isn't the case then `Task.fail` could be called to abort the `scrollTo`.

**Comment by MartinSStewart** [comment]
This might not be as easy as I thought. I tried implementing the override scroll feature and noticed that the smooth scrolling gets laggy if both `getViewportOf` and `setViewportOf` are called. My guess is that each task requires an animation frame so when getViewportOf is added, setViewportOf is called half as often.

**Comment by WhileTruu** [comment]
Yeah, iirc `requestAnimationFrame` for every `Task` is indeed the case, but it'd be nice to find these lines again. Maybe some sort of a hack using mapping/sequence allows bypassing it. :D
I'm not sure how I feel about relying on the internal implementation that much if it does.

**Comment by MartinSStewart** [comment]
I tried using `map2` to work around the issue but it didn't help. I think for my use case I'm going to have to resort to ports unfortunately.

**Comment by WhileTruu** [comment]
I don’t think that’s a bad choice in your case, the scrolling api could be designed the same/ some other nice way using ports :)

**Comment by MartinSStewart** [comment]
I'll go ahead and close this since it doesn't seem to be possible to implement within `elm-smooth-scroll`.
